### ISSUE TITLE
`make distcheck` fails if a *.vala file has translatable strings

### ISSUE THREAD

**Issue by alexkay** [tadeboro/Sampala#1]
To reproduce add `_("whatever")` somewhere in src/*.vala and `make distcheck`.

I worked this around by adding the *.c files to po/POTFILES.skip. I'm not an autotools expert, may be it's possible to fix this in a more generic way.

Error message:

```
...
srcdir=../../po /usr/bin/intltool-update -m
The following files contain translations and are currently not in use. Please
consider adding these to the POTFILES.in file, located in the po/ directory.

src/spek-window.c

If some of these files are left out on purpose then please add them to
POTFILES.skip instead of POTFILES.in. A file 'missing' containing this list
of left out files has been written in the current directory.
if [ -r missing -o -r notexist ]; then \
      exit 1; \
    fi
make[2]: *** [check] Error 1
make[2]: Leaving directory `/home/alex/Projects/spek/spek-0.1/_build/po'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/alex/Projects/spek/spek-0.1/_build'
make: *** [distcheck] Error 1
```

**Comment by tadeboro** [comment]
Did you try adding src/spek-window.c to po/POTFILES.skip as instructed by error message?

**Comment by alexkay** [comment]
As I mentioned I did just that and it works. However, it looks like a rather ugly work-around.

**Comment by tadeboro** [comment]
Why do you find this solution ugly? intltool cannot tell that file.c is actually created from file.vala and will thus try to extract strings from there too. If you look at my original project, all c files are listed inside POTFILES.skip

**Comment by alexkay** [comment]
It just looks backward to me that C files should be involved at all, the project is in Vala, not in C. My autofu is limited so I'm not sure if it's even feasible, feel free to close the issue if it's not.

**Comment by tadeboro** [comment]
Vala support in automake in implemented in such a way that c files are distributed along the vala sources. This makes it possible to compile vala applications even without valac on user's machine. This is the reason why you cannot ignore c file when using "stock" vala support in automake.

You can probably avoid doing this by either forcing automake not to distribute c files or telling intltool to ignore them, but doing this is beyond the scope of this simple application (and my knowledge for that matter;).

**Comment by alexkay** [comment]
Fair enough, I'm closing it then.

Thanks for doing this project by the way, it saved me quite a few hours :)
